# Generated by Django 4.2.18 on 2025-04-03 18:17

import core.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0067_issue_cached_display_title_es_and_more'),
        ('submission', '0082_article_abstract_es_article_title_es_section_name_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', core.model_utils.DynamicChoiceField(choices=[('translation', 'Translation')], default='translation', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedJournals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_journals', to='journal.journal')),
                ('links', models.ManyToManyField(blank=True, related_name='linked_to', through='hydra.JournalLink', to='journal.journal')),
            ],
        ),
        migrations.AddField(
            model_name='journallink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_link', to='hydra.linkedjournals'),
        ),
        migrations.AddField(
            model_name='journallink',
            name='to_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to', to='journal.journal'),
        ),
        migrations.CreateModel(
            name='LinkedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', core.model_utils.DynamicChoiceField(choices=[('translation', 'Translation')], default='translation', max_length=256)),
                ('from_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='submission.article')),
                ('to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to', to='submission.article')),
            ],
            options={
                'unique_together': {('from_article', 'to_article', 'relationship')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='journallink',
            unique_together={('parent', 'to_journal', 'link_type')},
        ),
    ]
